### ISSUE TITLE
Domain URL admin setting

### ISSUE THREAD

**Issue by dashaluna** [whyisjake/Simple-Instant-Articles-for-Facebook#38]
You will need to provide a URL that will be used for Instant Articles and add a meta tag to HTML's `<head>` tag. [Docs](https://developers.facebook.com/docs/instant-articles/claim-url).

**Comment by whyisjake** [comment]
Is this something that we need to do in the plugin? Looks like something just on the Facebook side.

**Comment by dashaluna** [comment]
As I understand it - you have to specify your domain (according to docs there are 3 options) when setting up the Instant Articles on the FB itself. That will generate the code that must be used in the meta tag to mark a page as eligible/trustworthy to be posted on FB Instant Articles, ex:

`<meta property="fb:pages" content="generated_code_from_FB" />`

@mattheu could you please confirm this.

**Comment by dashaluna** [comment]
Hm, actually not sure about this. I find the docs confusing :(
Going to close this.
