### ISSUE TITLE
Feed not found

### ISSUE THREAD

**Issue by klischka** [whyisjake/Simple-Instant-Articles-for-Facebook#43]
I installed and activated the plugin, but I gut 404 when trying to locate the feed or a preview of instant articles:
https://www.konradlischka.info/feed/fb
https://www.konradlischka.info/category/blog/feed/fb

Same problem with single posts:
https://www.konradlischka.info/2016/03/blog/lesetipp-kuenstliche-intelligenz-von-menschlicher-unterscheidet/fb-instant

Any idea what the reason could be? I did not find a similar issue here.
Feeds are all there: 
https://www.konradlischka.info/feed/
https://www.konradlischka.info/category/blog/feed/

**Comment by whyisjake** [comment]
Could you try flushing perms links?

**Comment by whyisjake** [comment]
@klischka I think there is a bug in the code, having the same issue. My apologies, digging in.

**Comment by klischka** [comment]
I just flushed permanent Links and now there are feeds, no 404s anymore. Thank you for your work and your advise! It is great that people share.
