### ISSUE TITLE
WordPress version compatibility

### ISSUE THREAD

**Issue by OriginalEXE** [whyisjake/Simple-Instant-Articles-for-Facebook#45]
Hello,

interested in giving this plugin a shot, but I am wondering why it says it's compatible only up to version 3.4.2?

Thanks

**Comment by whyisjake** [comment]
Mistake on behalf of the developer is the likely culprit. ;)

Using it on 4.4.2, and should be 4.5 ready.

**Comment by OriginalEXE** [comment]
Thanks, was thinking the same :) One more question, any reason to use this over https://github.com/Automattic/facebook-instant-articles-wp/ Do you maybe have insight into the difference between those two?

**Comment by whyisjake** [comment]
I don't @OriginalEXE. Been head down on this. :)

**Comment by whyisjake** [comment]
Updated here: https://github.com/whyisjake/Simple-Instant-Articles-for-Facebook/pull/48
